### ISSUE TITLE
@DataProvider runs before @BeforeClass

### ISSUE THREAD

**Issue by flocsy** [TNG/junit-dataprovider#114]
## Overview

- ( ) **Bug report.**

version 1.13.1

```
@RunWith(DataProviderRunner.class)
class MyTest {
    static Foo foo;

    @BeforeClass
    public static void beforeClass() {
        foo = new Foo();
    }

    @DataProvider
    public static Object[][] dataProviderCalculateFares() {
        foo.bar(); // thrown NPE because foo is not yet initialized
    }
}

```
I would expect @BeforeClass to run before anything else.

**Comment by aaschmid** [comment]
Thanks for the issue @flocsy. Due to some limitations and forces of JUnit4 internals it is not possible to evaluate `@BeforeClass` before `@DataProvider` :-(

Explaination and History:
I'm was not - and still I am not - very happy with that situation either and implemented a workaround, see https://github.com/TNG/junit-dataprovider/wiki/Features#beforeclass-support-junit4-only. Unfortunately it come out that this causes other unwanted behavior, see
* #49 - running a test suite causes all @BeforeClass instances to be run because filtering can only happen after evaluating dataproviders and generate the corresponding tests - and
* #64 - `@BeforeClass` is invoked at wrong time (and sometimes also multiple times) using abstract base classes.
If you are interested in more detail, don't hesitate to ask or read discussions in both above mentioned issues. 

I don't know if possible for you but JUnit 5 handles this much more appropriate and is meanwhile almost completely backwards compatible. Maybe it is worth a try with junit-dataprovider 2.0 and JUnit 5.

**Comment by flocsy** [comment]
thanks

**Comment by aaschmid** [comment]
Won't fix. For reason see my comment above. On any further question, don't hesitate to ask :-)

**Comment by raulvillalbamedina** [comment]
In version 1.10.0 this problem is ok

**Comment by raulvillalbamedina** [comment]
in version 1.10.3 is ok too. After in 1.10.4 the error appear

**Comment by aaschmid** [comment]
Yes, see https://github.com/TNG/junit-dataprovider/wiki/Features#beforeclass-support-junit4-only:

> Since: v1.9.2 Until: v1.10.3
