### ISSUE TITLE
When will it support non static dataprovider ?

### ISSUE THREAD

**Issue by wolfwestern** [TNG/junit-dataprovider#121]
## Overview

- ( ) **Feature request.** 
Sometimes, we wanna use variables in application.properties as the drivern data of dataprovider.
Have you thought about this feature ?

## Deliverables

- [ ] ...

**Comment by aaschmid** [comment]
Unfortunately, it is not possible with JUnit4 to create a meaningful non static because the tests are initialized in the runner's constructor where not instance is created of the test. I could of course create may own instance for executing the dataprovider but this would be a different instance than used for executing the test case.

Have you thought about JUnit5 Parameterized Tests and create a custom provider for your data?

**Comment by aaschmid** [comment]
Due to no further response on my question, I will close this issue. @wolfwestern don't hesitate to reopen in order to continue discussing options.
