### ISSUE TITLE
@DataProvider's splitBy should be only invoked when it is required

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#61]
Currently @DataProvider's splitBy explode is always performed, even though I don't need it since I only have got one parameter (containing a html string that contains the default splitBy character) in the test class. It is easy to workaround by supplying another splitBy value, but it increases verbosity.

So the explode should only be applied when the number of test method parameters is greater than 1.

**Comment by aaschmid** [comment]
It makes the code more confusing, though ;-)

**Comment by nikowitt** [comment]
A user does not care about that ;)

**Comment by aaschmid** [comment]
Hm ... now as I implemented the fix I am rather not sure if this is good due to consistency issues. I see your point above but is it really consistent behavior or not really obvious that code is *not* splitted by the splitter just because you just require a single argument and it is splitted in every other case?

**Comment by janschaefer** [comment]
I think this is fine. If you only have one argument, you do not expect that the string is splitted.
